#!/bin/sh

FULL_SELF=$(readlink -f "$0")
MY_PATH=$(dirname "$FULL_SELF")
CALLED_AS=$(basename "$0")

if [ -f $MY_PATH/ocamlrun ]; then
    $MY_PATH/ocamlrun $MY_PATH/_$CALLED_AS "$@"
else
    echo "error: can't find [$MY_PATH/ocamlrun]"
fi


